server {
    host        127.0.0.1
    port        8080
    server_name localhost
    root        www

    error_pages 404 www/errors/404.html
    error_pages 403 www/errors/403.html
    error_pages 500 www/errors/500.html

    client_max_body_size 1000000

    location / {
        index           index.html
        autoindex       off
        allow_methods   GET HEAD POST
    }

    location /upload {
        allow_methods        POST DELETE
        upload_path          www/upload
        client_max_body_size 10000000
    }

    location /files {
        allow_methods   GET HEAD
        autoindex       on
    }
}
