# Default Configuration for 42 Webserv
server {
	port 8080
	host 127.0.0.1
	server_name localhost;
	# Default error pages
	error_pages 404 ./errors/404.html
	error_pages 500 ./errors/500.html
    error_pages 403 ./errors/403.html
    # Default root of the site
    root  ./www
    client_max_body_size 10000000000

# Default settings for all requests
    location / {
        allow_methods GET POST
        autoindex on
        index index.html
    }

# Upload Test Path
    location /upload {
        root ./www
        method GET POST
        upload_path ./uploads
    }

# CGI Testing Path
    location /cgi-bin {
        root ./www
        method GET POST
        cgi_pass /usr/bin/python3
    }
}
