# Default Configuration for 42 Webserv
server {
	port 8080
	host 127.0.0.1
	server_name localhost;
    # الصفحات الافتراضية للأخطاء
	error_pages 404 errors/404.html
	error_pages 500 errors/500.html
    error_pages 403 errors/403.html
    # الجذر الافتراضي للموقع
    root  ./www
    client_max_body_size 1000000

    # الإعدادات الافتراضية لكل الطلبات
    location / {
        method GET POST
        autoindex on
        index index.html
    }

    # مسار اختبار الـ Upload
    location /upload {
        root /
        method GET POST
        upload_path /www/uploads
    }

    # مسار اختبار الـ CGI
    location /cgi-bin {
        root /
        method GET POST
        cgi_path /usr/bin/python3
    }
}
