server {
    port 8080
    host 127.0.0.1
    server_name webserv
    root www

    location / {
        allow_methods GET
        index index.html
    }

    location /images {
        autoindex on
    }
}
