server {
    port 8090
    host 127.0.0.1    
    server_name app1
    root www
}

server {
    port 8090 # Virtual Hosting
    host 127.0.0.1      
    server_name app2
    root www/folder
}

server {
    port 7070           # Multiple Ports
    host 127.0.0.1      
    server_name app_special
    root www/folder
}