server {
    host        127.0.0.1
    port        8080
    server_name siteA
    root        www/siteA

    error_pages 404 www/errors/404.html

    location / {
        index         index.html
        autoindex     off
        allow_methods GET HEAD
    }
}

server {
    host        127.0.0.1
    port        8081
    server_name siteB
    root        www/siteB

    error_pages 404 www/errors/404.html

    location / {
        index         index.html
        autoindex     off
        allow_methods GET HEAD POST DELETE
    }

    location /upload {
        allow_methods        POST DELETE
        upload_path          www/siteB/upload
        client_max_body_size 2000000
    }
}
