# Full Configuration for POST and CGI testing
server {
    port 8080
    host 127.0.0.1
    server_name webserv
    root www

    # المسار الرئيسي لاختبار الـ POST العادي
    location /put_test/ {
        allow_methods POST
        upload_path ./uploads/
    }

    # المسار الخاص بـ CGI (سيرفع الملف عبر السكريبت)
    location /upload {
        allow_methods POST
        cgi_pass ./www/cgi-bin/upload.py
    }

    # اختبار تحديد حجم الـ Body
    location /post_body {
        allow_methods POST
        client_max_body_size 100
    }

    # مسار افتراضي للملفات الثابتة
    location / {
        allow_methods GET
        index index.html
    }
}
