server {
    host        127.0.0.1
    port        8080
    server_name localhost
    root        www

    error_pages 404 www/errors/404.html

    location / {
        index         index.html
        autoindex     off
        allow_methods GET HEAD
    }

    # Redirect /old to /new
    location /old {
        redirect /new
    }

    # Directory listing enabled
    location /public {
        autoindex     on
        allow_methods GET HEAD
    }

    # Only GET allowed — POST/DELETE return 405
    location /readonly {
        allow_methods GET HEAD
        autoindex     off
    }
}
