server {
    port 8080
    host 127.0.0.1
    server_name webserv
    
    # الـ root الأساسي (المكان الذي تشغلون منه السيرفر)
    root www
    
    # حجم افتراضي كبير جداً عشان ما يفشل التستر في اختبارات الضغط والملفات الكبيرة
    client_max_body_size 1000000000

    # 1. مسار / مسموح له GET فقط
    location / {
        allow_methods GET
        index index.html
    }

    # 2. أي ملف ينتهي بـ .bla يجب أن يقبل POST ويشغل cgi_tester
    location .bla {
        allow_methods POST
        cgi_pass ./cgi_tester
    }

    # 3. مسار /post_body يقبل POST ولكن بحجم أقصى 100 بايت فقط
    location /post_body {
        allow_methods POST
        client_max_body_size 100
    }

    # 4. مسار /directory/ يقبل GET، والـ root تبعه هو YoupiBanane، والـ index هو youpi.bad_extension
    location /directory {
        allow_methods GET POST
        root YoupiBanane
        index youpi.bad_extension
    }
    
    # مسار إضافي مخصص لاختبارات الرفع (PUT/POST) إذا لزم الأمر
    location /put_test/ {
        allow_methods PUT
        upload_path ./
    }
}
