server {
    port 8093
    host 127.0.0.1
    server_name methods.local;
    error_pages 405 ./errors/405.html
    root ./www
    client_max_body_size 1000000

    # Allowed: GET only
    location /only_get {
        allow_methods GET
        index index.html
    }

    # Allowed: GET and POST
    location /get_post {
        allow_methods GET POST
        index index.html
    }

    # Disallowed methods scenario (no PUT/DELETE)
    location /no_put {
        allow_methods GET POST
    }
}
