server {
    port 8084
    host 127.0.0.1
    server_name multi1.local;
    root ./www
    client_max_body_size 10000000
    location / {
        allow_methods GET
        index index.html
    }
}

server {
    port 8085
    host 127.0.0.1
    server_name multi2.local;
    root ./www
    client_max_body_size 10000000
    location / {
        allow_methods GET
        index index.html
    }
}
