server {
    port 8090
    host 127.0.0.1
    server_name get.local;
    error_pages 404 ./errors/404.html
    root ./www
    client_max_body_size 1000000

    location / {
        allow_methods GET
        index index.html
        autoindex off
    }

    location /get.html {
        allow_methods GET
    }
}
