server {
    port 8080
    host 127.0.0.1
    server_name localhost;
    error_pages 404 ./errors/404.html
    error_pages 500 ./errors/500.html
    error_pages 403 ./errors/403.html
    error_pages 400 ./errors/400.html
    error_pages 405 ./errors/405.html
    error_pages 413 ./errors/413.html
    # project root (relative to repo)
    root ./www
    client_max_body_size 10000000

    location / {
        allow_methods GET
        index index.html
        autoindex off
    }

    location /get.html {
        allow_methods GET
    }

    # static file which should reject POST (tests 405)
    location /post.html {
        allow_methods GET
    }

    location /auto_on {
        allow_methods GET
        autoindex on
    }

    location /cgi-bin {
        root ./www
        allow_methods GET POST
        cgi_pass /usr/bin/python3
    }
}
