#!/usr/bin/env python3

print("Content-Type: text/html\r\n\r\n")
print("<html>")
print("<head><title>CGI Test</title></head>")
print("<body>")
print("<h1>CGI Script is Working!</h1>")
print("<p>This response was generated by your Python CGI script.</p>")
print("</body>")
print("</html>")
